backend = "xrender"
shadow = true;
no-dock-shadow = true;
shadow-radius = 4;
shadow-offset-x = -4;
shadow-offset-y = -4;

fading = false;
# fading = true;
# fade-delta = 10;
# fade-in-step = 0.08;
# fade-out-step = 0.08;

detect-client-opacity = true;

vsync = false;
use-damage = false;
unredir-if-possible = true;
