backend = "xrender"
shadow = true;
no-dock-shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;

fading = false;
# fading = true;
# fade-delta = 10;
# fade-in-step = 0.08;
# fade-out-step = 0.08;

detect-client-opacity = true;

vsync = false;
use-damage = true

no-ewmh-fullscreen = true;
unredir-if-possible = false;

opacity-rule = [];
detect-client-opacity = false;
